language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: hHH14VIZoV4hPh5dzX1p1SCQmXfY3lHPS5c8VdBWtfvK/VnLk8stjWpcCwkYYb25RCunkeyQK4RzsfGP+tsJi/lVMEsdrUCzhUvgJtwLu6avFmg6rbqr45jpSWuZQh29l4hkhcf6V1Pof042dbwUohC9FiopjraCGOn3EmhUiIPPmnXPGIlkYxZgKjQRtz7Y/TVHhhZUvKexMWMQVkL1EohGXjqHbddV66/0LvQRkAQcuYAthweCH+y5Xc1KNBTc0prVHKbvy5YlIPYEQxvOlsOYeNo0kQUAmcDdGEssVa84+BvTP9x81laJG09LWrPSo1zMIhCCNfdSVZfVfbUQ6rhTxx9gbTJvP8yZQ/uaednBU92fG1XZv284GARDQXyxEeLRB4IuIhqWoBLG0+rcKiyWe3VrvYut+4m0wKXUDjdgD7q5bvtGTLretxBy1se9O188w2fIVLOCIHL1B4SYTXcwXDkRYcZYUiCrnw0ivjxzr3exopTuiQRE2zPc1uSZjUFpwDWF5mddu32Fa10KdGDeKEeI2JI6DvT9650ixG2ZBbZeDEPAhkIiu3FGMX1mOVBRSHcDNEgX98e6LQsIA40WLUcBvlHUblUBKKzdVZiffD8LlESveZrfqoBRXv8dCEAgCQHI03tOeYn/XBeBINx0O0BebOzIrfFamDiV8Ek=
  file: target/gnuob-api.jar
  skip_cleanup: true
  on:
    tags: true
